{% set data = load_setup_py_data() %}

package:
  name: axl
  version: {{ data.get('version').replace('-', '_') }}

source:
  path: ../

build:
  number: 0

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - pywin32
    - pandas

